services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
